config/routes.rb
Rails.application.routes.draw do
  root to:'top#index'
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :content, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    # 現在ログイン中のユーザが存在しない場合、ログインページにリダイレクトさせる。
    if current_user.name.empty?
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = current_user.feeds.build(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end
  def ensure_correct_user
    @feed = Feed.find_by(id: params[:id])
    if current_user.name.empty?
      flash[:notice] = "ログインしてください"
      redirect_to new_session_path
    else
      if @feed.user_id != current_user.id
        flash[:notice] = "権限がありません"
        redirect_to new_session_path
      end
    end
  end
  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :コメント %>
    <div class="content">
      <%= form.text_field :content, size: 50%>
    </div>
    <div class="feed_image">
      <%= image_tag(@feed.image.url, class: 'feed_img') if @feed.image && @feed.image.url %>
    </div>
    <div class="file_field">
      <%= form.file_field :image %>
    </div>
    <div class="hidden_field">
      <%= form.hidden_field :image_cache %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit "投稿する"%>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1 class="confirm_title">確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <p class="confirmcontent">コメント:<%= @feed.content %></p>
  <div class="content">
    <%= form.hidden_field :content %>
  </div>
  <div class="feed_image">
    <%= image_tag(@feed.image.url, class: 'feed_img') if @feed.image && @feed.image.url %>
  </div>
  <div class="image_cache">
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit "投稿する" %>
  </div>
<% end %>
<%= form_with(model:@feed, url: new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <div class="back">
    <%= form.submit "戻る", name: "back" %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1 class="title_edit">編集画面</h1>

<%= render 'form', feed: @feed %>
<div class="edit_to">
    <%= link_to 'Show', @feed %> |
    <%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/index.html.erb
<table class="table">
  <tbody>
    <% @feeds.each do |feed| %>
      <% if current_user == nil %>
      <tr>
        <td><%= feed.user.name %></td>
        <td><%= link_to '投稿をみる-', feed %></td>
        <td ><%= feed.content %></td>
        <td><%= feed.image %></td>
      </tr>
      <% elsif feed.user_id == current_user.id %>
      <tr>
        <td><%= feed.user.name %></td>
        <td><%= link_to '投稿をみる-', feed %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '編集する', edit_feed_path(feed) %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '削除する', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td ><%= feed.content %></td>
        <td><%= feed.image %></td>
      </tr>
      <% else %>
      <tr>
        <td><%= feed.user.name %>
        <td><%= link_to '投稿をみる-', feed %></td>
        <td ><%= feed.content %></td>
        <td><%= feed.image %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/feeds/new.html.erb
<h1 class="new_feed">新しい投稿</h1>

<%= render 'form', feed: @feed %>

<div class="back">
<%= link_to '戻る', feeds_path %>
</div>

app/views/feeds/show.html.erb
<h1 class="show">詳細画面</h1>
  <div class="content">
    コメント: <%= @feed.content %>
  </div>
  <div class="feed_image">
    <%= image_tag @feed.image.url, class: 'feed_img' %>
  </div>
<% if current_user == nil %>
  <div class="back">
    <%= link_to 'Back', feeds_path %>
  </div>
<% elsif @feed.user_id == current_user.id %>
  <div class="edit">
    <%= link_to 'Edit', edit_feed_path(@feed) %>
  </div>
  <div class="back">
    <%= link_to 'Back', feeds_path %>
  </div>
<% else %>
  <div class="back">
  <%= link_to 'Back', feeds_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="feeds.scss">
  </head>
  <header class="header">
    <div class="logo">
      <%= image_tag 'f.png', :size => '30x30' %>
    </div>
    <% if logged_in? %>
      <div class="login-username">
        <p>ログインユーザー名: <%= current_user.name %></p>
      </div>
      <div class="newfeed">
        <%= link_to '作成', new_feed_path %>
      </div>
      <div class="user_logout">
        <div class="logout">
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        </div>
      </div>
    <% else %>
      <div class="user_status">
        <div class="signup">
          <%= link_to "Sign up", new_user_path %>
        </div>
        <div class="login">
          <%= link_to "Login", new_session_path %>
        </div>
      </div> 
    <% end %>
    </div>
  </header>
  <p id="notice"><%= notice %></p>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<head>
  <meta charset="UTF-8">
</head>
  <h1 class="title_feeds">Facebook Clone</h1>
<%= form_with(model: @feed, local: true) do |form| %>
  <div class="submit_index">
    <%= link_to "投稿一覧へ", feeds_path %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class="title_signup">Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="label_name">
    <%= f.label :name %>
  </div>
  <div class="text_field_name">
    <%= f.text_field :name %>
  </div>
  <div class="label_email">
    <%= f.label :email %>
  </div>
  <div class="user_email_field">
    <%= f.email_field :email %>
  </div>
  <div class="label_password">
    <%= f.label :password %>
  </div>
  <div class="user_password_field">
    <%= f.password_field :password %>
  </div>
  <div class="label_password_confirmation">
    <%= f.label :password_confirmation %>
  </div>
  <div class="password_field_password_confirmation">
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="submit_createacount">
    <%= f.submit "アカウント作成" %>
  </div>
<% end %>
<div class="to_top">
  <%= link_to 'トップ画面へ', "/" %>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
    <h1 class="logined"><%= @user.name %>さんはログインしました。</h1>
    <p class="email_address">メールアドレス: <%= @user.email %></p>
    <div class="submit_index">
        <%= link_to '投稿一覧へ', feeds_path %>
    </div>
<% else %>
    <h1 class="logined"><%= @user.name %>さんの登録が完了しました。ログインしてください。</h1>
    <p class="email_address">メールアドレス: <%= @user.email %></p>
<% end %>